[package]
name = "speck-probe"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
indicatif = "0.18.4"
primitive-types = "0.14"
crossbeam = "0.8"
colored = "3"
console = "0.16"
num_cpus = "1.17"
textwrap = "0.16"
terminal_size = "0.4"
human_format = "1"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22"
thiserror = "2"
toml = "1"
csv = "1"
walkdir = "2.5"
rayon = "1.11"
seq-macro = "0.3.6"
paste = "1"
multiversion = "0.8"
strum = { version = "0.28.0", features = ["derive"] }
bytemuck = { version = "1", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.8", features = ["csv_output"] }
rstest = "0.26"
bytemuck = { version = "1", features = ["avx512_simd", "aarch64_simd"] }
serde_json = "1"

[[bench]]
name = "speck_scalar_benches"
harness = false

[[bench]]
name = "speck_sse2_benches"
harness = false

[[bench]]
name = "speck_avx2_benches"
harness = false

[[bench]]
name = "speck_avx512_benches"
harness = false

[[bench]]
name = "speck_neon_benches"
harness = false

[[bench]]
name = "engine_scalar_benches"
harness = false

[[bench]]
name = "engine_sse2_benches"
harness = false

[[bench]]
name = "engine_avx2_benches"
harness = false

[[bench]]
name = "engine_avx512_benches"
harness = false

[[bench]]
name = "engine_neon_benches"
harness = false