[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
runtime = { path = "../runtime" }
speck = { path = "../speck" }
clap = { version = "4.6.0", features = ["derive"] }
indicatif = "0.18.4"
primitive-types = "0.14"
crossbeam = "0.8"
colored = "3"
console = "0.16"
num_cpus = "1.17"
textwrap = "0.16"
terminal_size = "0.4"
human_format = "1"