# bluetooth
blacklist btusb
blacklist btintel
blacklist btbcm
blacklist btrtl
blacklist btmtk
blacklist bluetooth

# audio
blacklist snd_hda_intel
blacklist snd_hda_codec_hdmi
blacklist snd_hda_codec
blacklist snd_usb_audio
blacklist snd_pcm
blacklist snd_timer
blacklist snd

# TPM
blacklist tpm
blacklist tpm_crb
blacklist tpm_tis

# serial
blacklist 8250_pnp
blacklist 8250

# storage — żaden NVMe nie jest używany
blacklist nvme
blacklist nvme_core

# network (jeśli na 100% offline)
blacklist igc