blacklist btusb
blacklist btintel
blacklist btbcm
blacklist btrtl
blacklist btmtk
blacklist bluetooth

blacklist snd_hda_intel
blacklist snd_hda_codec_hdmi
blacklist snd_hda_codec
blacklist snd_usb_audio
blacklist snd_pcm
blacklist snd_timer
blacklist snd

blacklist tpm
blacklist tpm_crb
blacklist tpm_tis

blacklist 8250_pnp
blacklist 8250

blacklist nvme
blacklist nvme_core

blacklist igc