[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
ParallelDownloads = 5

[core]
Server = https://archive.archlinux.org/repos/2026/05/12/$repo/os/$arch

[extra]
Server = https://archive.archlinux.org/repos/2026/05/12/$repo/os/$arch