[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
speck = { path = "../speck" }
multiversion = "0.8"
thiserror = "2"
strum = { version = "0.28", features = ["derive"] }

[dev-dependencies]
criterion = "0.8"
rstest = "0.26"

[[bench]]
name = "iterator_benches"
harness = false

[[bench]]
name = "search_engine_benches"
harness = false
