mitigations=off
nosmt
transparent_hugepage=always
processor.max_cstate=1
amd_pstate=active
nowatchdog
nosoftlockup
nmi_watchdog=0
audit=0
skew_tick=1
tsc=reliable
numa_balancing=disable
idle=poll
rcu_nocbs=0-15
nohz_full=1-15
irqaffinity=0
noautogroup
sched_migration_cost_ns=5000000
