title    Arch Linux install medium (%ARCH%, UEFI)
sort-key 01
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux
initrd   /%INSTALL_DIR%/boot/amd-ucode.img
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux.img
options  archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% mitigations=off copytoram transparent_hugepage=always amd_pstate=active nowatchdog nosoftlockup nmi_watchdog=0 audit=0 skew_tick=1 tsc=reliable numa_balancing=disable rcu_nocbs=1-15 nohz_full=1-15 irqaffinity=0 noautogroup cow_spacesize=16G
